spring:
  datasource:
    # 이제 테스트가 DB 없어도 실행된다.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:site1_test # DB이름 : site1, 테스틑용이니깐 굳이 실DB가 없어도 된다. 그래서 h2사용(인메모리)
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false